// Code generated by "stringer -type=EthicKind"; DO NOT EDIT.

package ethics

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EthicGestaltConsciousness-1]
	_ = x[EthicAuthoritarian-2]
	_ = x[EthicEgalitarian-3]
	_ = x[EthicXenophobic-4]
	_ = x[EthicXenophilic-5]
	_ = x[EthicMilitarist-6]
	_ = x[EthicPacifist-7]
	_ = x[EthicSpiritualist-8]
	_ = x[EthicMaterialist-9]
	_ = x[EthicKindMAX-10]
}

const _EthicKind_name = "EthicGestaltConsciousnessEthicAuthoritarianEthicEgalitarianEthicXenophobicEthicXenophilicEthicMilitaristEthicPacifistEthicSpiritualistEthicMaterialistEthicKindMAX"

var _EthicKind_index = [...]uint8{0, 25, 43, 59, 74, 89, 104, 117, 134, 150, 162}

func (i EthicKind) String() string {
	i -= 1
	if i < 0 || i >= EthicKind(len(_EthicKind_index)-1) {
		return "EthicKind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _EthicKind_name[_EthicKind_index[i]:_EthicKind_index[i+1]]
}
