// Code generated by "stringer -type=AggressionLevel"; DO NOT EDIT.

package content

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AggressionLevelPeaceful-1]
	_ = x[AggressionLevelNeutral-2]
	_ = x[AggressionLevelAggressive-3]
	_ = x[AggressionLevelHostile-4]
	_ = x[AggressionLevelWarlike-5]
	_ = x[AggressionLevelMAX-6]
}

const _AggressionLevel_name = "AggressionLevelPeacefulAggressionLevelNeutralAggressionLevelAggressiveAggressionLevelHostileAggressionLevelWarlikeAggressionLevelMAX"

var _AggressionLevel_index = [...]uint8{0, 23, 45, 70, 92, 114, 132}

func (i AggressionLevel) String() string {
	i -= 1
	if i < 0 || i >= AggressionLevel(len(_AggressionLevel_index)-1) {
		return "AggressionLevel(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AggressionLevel_name[_AggressionLevel_index[i]:_AggressionLevel_index[i+1]]
}
