// Code generated by "stringer -type=MagicLevel"; DO NOT EDIT.

package content

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MagicLevelNone-1]
	_ = x[MagicLevelLow-2]
	_ = x[MagicLevelMedium-3]
	_ = x[MagicLevelHigh-4]
	_ = x[MagicLevelEpic-5]
}

const _MagicLevel_name = "MagicLevelNoneMagicLevelLowMagicLevelMediumMagicLevelHighMagicLevelEpic"

var _MagicLevel_index = [...]uint8{0, 14, 27, 43, 57, 71}

func (i MagicLevel) String() string {
	i -= 1
	if i < 0 || i >= MagicLevel(len(_MagicLevel_index)-1) {
		return "MagicLevel(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MagicLevel_name[_MagicLevel_index[i]:_MagicLevel_index[i+1]]
}
