// Code generated by "stringer -type=MilitaryType"; DO NOT EDIT.

package content

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MilitaryTypeNone-1]
	_ = x[MilitaryTypeMilitia-2]
	_ = x[MilitaryTypeMercenary-3]
	_ = x[MilitaryTypeProfessional-4]
	_ = x[MilitaryTypeConscript-5]
	_ = x[MilitaryTypeElite-6]
	_ = x[MilitaryTypeMAX-7]
}

const _MilitaryType_name = "MilitaryTypeNoneMilitaryTypeMilitiaMilitaryTypeMercenaryMilitaryTypeProfessionalMilitaryTypeConscriptMilitaryTypeEliteMilitaryTypeMAX"

var _MilitaryType_index = [...]uint8{0, 16, 35, 56, 80, 101, 118, 133}

func (i MilitaryType) String() string {
	i -= 1
	if i < 0 || i >= MilitaryType(len(_MilitaryType_index)-1) {
		return "MilitaryType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MilitaryType_name[_MilitaryType_index[i]:_MilitaryType_index[i+1]]
}
