// Code generated by "stringer -type=MultiRaceType"; DO NOT EDIT.

package content

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Domination-1]
	_ = x[Coexistence-2]
}

const _MultiRaceType_name = "DominationCoexistence"

var _MultiRaceType_index = [...]uint8{0, 10, 21}

func (i MultiRaceType) String() string {
	i -= 1
	if i < 0 || i >= MultiRaceType(len(_MultiRaceType_index)-1) {
		return "MultiRaceType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MultiRaceType_name[_MultiRaceType_index[i]:_MultiRaceType_index[i+1]]
}
