// Code generated by "stringer -type=TechLevel"; DO NOT EDIT.

package content

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TechLevelPrePrimitive-1]
	_ = x[TechLevelPrimitive-2]
	_ = x[TechLevelMedieval-3]
	_ = x[TechLevelModern-4]
	_ = x[TechLevelFuturistic-5]
	_ = x[TechLevelMAX-6]
}

const _TechLevel_name = "TechLevelPrePrimitiveTechLevelPrimitiveTechLevelMedievalTechLevelModernTechLevelFuturisticTechLevelMAX"

var _TechLevel_index = [...]uint8{0, 21, 39, 56, 71, 90, 102}

func (i TechLevel) String() string {
	i -= 1
	if i < 0 || i >= TechLevel(len(_TechLevel_index)-1) {
		return "TechLevel(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TechLevel_name[_TechLevel_index[i]:_TechLevel_index[i+1]]
}
